---
name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

permissions: {}

jobs:
  release:
    permissions:
      contents: write # Required to create the GitHub release.
    uses: glueckkanja/gkvm-tools/.github/workflows/release.yml@22733ccd383819c6705f83b40c425be0e1b9dcf8 # v0.1.4
