---
name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

permissions: {}

jobs:
  release:
    permissions:
      contents: write # Required to create the GitHub release.
    uses: glueckkanja/gkvm-tools/.github/workflows/release.yml@d47dce61d874d09f64fa82877e2f966bf033dea9 # v0.1.6
