---
name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

permissions: {}

jobs:
  release:
    uses: glueckkanja/gkvm-tools/.github/workflows/release.yml@5a4711858276e084da91a1f77e419c00806e90a3 # v0.1.0
